# -*- coding: utf-8 -*-
"""diabetes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-KYWpG-upVKyOWGu8B2Ji-TiaqFrqq7K
"""

from google.colab import files
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
uploaded = files.upload()
import io 
df = pd.read_csv(io.BytesIO(uploaded['pima-indians-diabetes.csv']))

norm_cols = ['Number_pregnant', 'Glucose_concentration', 'Blood_pressure', 'Triceps','Insulin', 'BMI', 'Pedigree']

df[norm_cols] = df[norm_cols].apply(lambda x: ((x-x.min())/(x.max()-x.min())))

num_preg = tf.feature_column.numeric_column('Number_pregnant')
plasma_gluc = tf.feature_column.numeric_column('Glucose_concentration')
dias_press = tf.feature_column.numeric_column('Blood_pressure')
tricep = tf.feature_column.numeric_column('Triceps')
insulin = tf.feature_column.numeric_column('Insulin')
bmi = tf.feature_column.numeric_column('BMI')
diabetes_pedigree = tf.feature_column.numeric_column('Pedigree')
age = tf.feature_column.numeric_column('Age')

group = tf.feature_column.categorical_column_with_vocabulary_list('Group',['A','B','C','D'])
age_bucket = tf.feature_column.bucketized_column(age,boundaries=[20,30,40,50,60,70,80])
feat_cols = [num_preg ,plasma_gluc,dias_press ,tricep ,insulin,bmi,diabetes_pedigree ,group, age_bucket]
x_data = df.drop('Class',axis = 1)
y_data = df['Class']
X_train, X_test, y_train, y_test = train_test_split(x_data,y_data,test_size = 0.3)

input = tf.compat.v1.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,batch_size=10,num_epochs=1000,shuffle=True)
model = tf.estimator.LinearClassifier(feature_columns=feat_cols, n_classes=2)
model.train(input_fn = input,steps=1000)

